markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
permalink: /blog/:year/:month/:day/:title
plugins: [jekyll-paginate]
paginate: 10
paginate_path: /blog/page:num/
title: Nate Woodward
description: Linux Admin
future: false
